//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinally.Areas.AdminPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDH
    {
        public string maCTDH { get; set; }
        public string maDH { get; set; }
        public string maSP { get; set; }
        public Nullable<int> soluong { get; set; }
        public string color { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
