//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinally.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public long IdUser { get; set; }
        public long id { get; set; }
        public string tensp { get; set; }
        public string image { get; set; }
        public string thoigianbaohanh { get; set; }
        public Nullable<decimal> dongiasp { get; set; }
        public Nullable<decimal> dongiakhuyenmai { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaythaydoi { get; set; }
        public string size { get; set; }
        public Nullable<bool> nosize { get; set; }
        public string mausac { get; set; }
        public Nullable<long> mansx { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual TKUser TKUser { get; set; }
    }
}
