//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinally.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public long id { get; set; }
        public string ten { get; set; }
        public string image { get; set; }
        public string motasp { get; set; }
        public string thoigianbaohanh { get; set; }
        public Nullable<int> soluongsp { get; set; }
        public Nullable<decimal> dongiasp { get; set; }
        public Nullable<long> mansx { get; set; }
        public string mausac { get; set; }
        public string size { get; set; }
        public Nullable<bool> nosize { get; set; }
        public Nullable<int> daban { get; set; }
        public Nullable<long> maloai { get; set; }
        public Nullable<decimal> dongiakhuyenmai { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public string tags { get; set; }
        public Nullable<long> Admin { get; set; }
    
        public virtual Admin Admin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual loaisanpham loaisanpham { get; set; }
    }
}
